// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUaaQ4InNyATv3pkOkoVP__oX19ees6Ws',
    appId: '1:912875241727:android:44313c2a481db97f000cca',
    messagingSenderId: '912875241727',
    projectId: 'app-personal-trainer-48012',
    storageBucket: 'app-personal-trainer-48012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0IxH541NNn6TEqnjo07i3YmYeGQ2klU',
    appId: '1:912875241727:ios:1e79a6fd76ec5912000cca',
    messagingSenderId: '912875241727',
    projectId: 'app-personal-trainer-48012',
    storageBucket: 'app-personal-trainer-48012.firebasestorage.app',
    iosBundleId: 'com.projetosales.appPersonalTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0IxH541NNn6TEqnjo07i3YmYeGQ2klU',
    appId: '1:912875241727:ios:1e79a6fd76ec5912000cca',
    messagingSenderId: '912875241727',
    projectId: 'app-personal-trainer-48012',
    storageBucket: 'app-personal-trainer-48012.firebasestorage.app',
    iosBundleId: 'com.projetosales.appPersonalTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqOqkudOXgcjSOsFPD5D9-rcguPkqp-w8',
    appId: '1:912875241727:web:d73532d4f8a80f36000cca',
    messagingSenderId: '912875241727',
    projectId: 'app-personal-trainer-48012',
    authDomain: 'app-personal-trainer-48012.firebaseapp.com',
    storageBucket: 'app-personal-trainer-48012.firebasestorage.app',
    measurementId: 'G-RP3ERGM63H',
  );
}
